### ISSUE TITLE
Could you help provide the license file of this package?

### ISSUE THREAD

**Issue by phthhieu** [tungv/brn#6]
For example https://github.com/facebook/react/blob/main/LICENSE

**Comment by tungv** [comment]
https://github.com/tungv/brn/commit/204c6adbb772cf1a88471336cfe1dbdd85230b90

**Comment by tungv** [comment]
do you need a new NPM version?

**Comment by tungv** [comment]
https://www.npmjs.com/package/brn with version 1.1.3 is published.
Thanks for raising this.

**Comment by phthhieu** [comment]
@tungv thanks for your support 🏩
